# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samplenan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(946, 979)
        self.nifti_imgs = QtWidgets.QLabel(Dialog)
        self.nifti_imgs.setGeometry(QtCore.QRect(130, 220, 91, 71))
        self.nifti_imgs.setText("")
        self.nifti_imgs.setObjectName("nifti_imgs")
        self.imageslider = QtWidgets.QSlider(Dialog)
        self.imageslider.setGeometry(QtCore.QRect(100, 150, 160, 22))
        self.imageslider.setOrientation(QtCore.Qt.Horizontal)
        self.imageslider.setObjectName("imageslider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
